### ISSUE TITLE
10.6.7 sleep

### ISSUE THREAD

**Issue by zprood** [adlan/BCM5722D#3]
```
 With the new sources code compiled in the 10.6.7 xcode  3.2.5 ver. Network Card:BCM5906.
 It seems everything work well, but when wakeup from a short time or longer, cause different phenomenons,
 First, in a short time like 5 minutes or 30 minutes etc. And when wakeup from sleep, the network is not work though, even the drive is load with kextstat command checking, also the system preferences shows it is connected but can't get network work.    
 Second, if the sleep time is longer than an hour, when get it wakeup, the network disconnected, no signal.
 But, when back to the older version, it works like a charm. And all above issue can be solved by using Kextloan & Kextunload command in the terminal.

Regards zprood.
```

**Comment by adlan** [comment]
since some users reported the same problem - so i can confirm that this happens after updating to 10.6.7. I'll update my machine to 10.6.7 and; try to reproduce and rectify this issues as soon as possible.

thanks,

**Comment by zprood** [comment]
Thanks for this project, I am appreciate that you keep working on it.

**Comment by adlan** [comment]
fixed, a heisenbug, maybe

**Comment by zprood** [comment]
Thanks a lot. Great job man.

**Comment by gleng** [comment]
On Lion GM, my BCM5754 [14e4:167a] will show "cable disconnected" after resuming from sleep. Doing a kextunload and then kextload will allow me to regain network functionality.

Other than that the driver seems stable

Thanks
