### ISSUE TITLE
Can't work for BCM5787 

### ISSUE THREAD

**Issue by gamble** [adlan/BCM5722D#4]
PC is Dell 330
Broadcom NetLink BCM5787 PCI-E Gigabit Ethernet Controller
ID: E4 14 9B 16
OS: Snow Leopard 10.6.6

**Comment by adlan** [comment]
hi,
can you try this kext
http://cl.ly/3e3l2N2t1n242a3O0T0I

and send me the log?

**Comment by gamble** [comment]
Hi,
I try this one, but nothing happened.
After boot os, I can't find out any info about BCM5722 in
/var/log/kernel.log and system.log.
Also I use command 'kextstat' and can't find the BCM5722 in loaded kexts.
When I manually load this kext( 'kextutil'), this kext can be loaded
successfully,
but also nothing happened on my BCM5787.

**Comment by adlan** [comment]
i see,
you should find the log message in /var/log/kernel.log
where did you install the kext?

try loading the kext manually and after the kext is loaded, can you send me
1. the output of _ifconfig -a_
2. the log message, take the line starting with "BCM5722D"

**Comment by gamble** [comment]
Hi,
I put the kext at /System/Library/Extensions/BCM5722D.kext
Below is the shell command log:(en1 is my another netware card, it's worked)

```

bash-3.2# kextstat | grep 'BCM'

bash-3.2# kextutil /System/Library/Extensions/BCM5722D.kext

bash-3.2# kextstat | grep 'BCM'

   91    0 0x21664000 0x9000     0x8000     my.name.adlan.BCM5722D (1)
<62 13 5 4 3 1>

bash-3.2# ifconfig -a

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384

inet6 ::1 prefixlen 128

inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1

inet 127.0.0.1 netmask 0xff000000

gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280

stf0: flags=0<> mtu 1280

en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500

ether e0:05:c5:ea:d9:a2

inet6 fe80::e205:c5ff:feea:d9a2%en1 prefixlen 64 scopeid 0x4

inet 192.168.1.109 netmask 0xffffff00 broadcast 192.168.1.255

media: autoselect (100baseTX <full-duplex,flow-control>)

status: active

bash-3.2# cat /var/log/kernel.log | grep 'BCM'

bash-3.2# cat /var/log/kernel.log | grep 'BCM57'

```

**Comment by adlan** [comment]
that's weird. it should at least, shows a build date/time message.

normally kextd will automatically load the kext if it found the matching pci id for the hardware on system startup, but in your case, the kext isn't loaded at all.
- do you have any other kext for the same hardware in S/L/E ?
- do you have other os installed on that machine?, did the card works there?

**Comment by gamble** [comment]
ok, I will check.
Because I install a cracked mac os (hazard 10.6.6), not the pure 10.6.6, so
maybe
there are some kexts about BCM57*\* in the S/L/E.
Thank you for help, I will send you the result ASAP.

ps:
The card can work in Windows.
I had installed a BCM5787M.kext by my hex modified for new device ID(169b),
and something happened, and I can setup the en0, but it can't work
correctly.

**Comment by adlan** [comment]
i've downloaded the broadcom kext provided in the distro site to check if any of the kext defines your card pci id and
I couldn't find any. so, theoretically BCM5722D.kext should be loaded automatically on system startup. what puzzled me more is there isn't any logged message although the kext has been loaded successfully.

have you tried removing BCM5722D.kext and reinstalling it?

**Comment by guoxj** [comment]
i have the same problem.not working for my dell 330,SL10.6.7.
It seems that it hasnot been loaded.

**Comment by gamble** [comment]
adlan had already fixed this problem, pls get the lastest version from him

**Comment by guoxj** [comment]
YES!! it works!!!  thanks adlan! thanks for your excellent work!

**Comment by adlan** [comment]
@gamble, thanks!

@guoxj, glad to hear it's working for you!
