### ISSUE TITLE
Lenovo s10e (4333) no ethernet recognized

### ISSUE THREAD

**Issue by jackblow** [adlan/BCM5722D#5]
Tried to install BCM5722D.kext. with KextWizard and with kexthelper 0.7. 
My ethernet onboard device is a BCM5906M.
My ethernet does not work

**Comment by JanX2** [comment]
Strange. It works for me on my S10e.

**Comment by JanX2** [comment]
Did you open Network Prefs after installing? It probably won't show up otherwise.

**Comment by jackblow** [comment]
Yes I have open but nothing.
I have found a driver that works: http://code.google.com/p/osx-bcm5906m/

2011/6/9 JanX2 reply@reply.github.com:

**Comment by jackblow** [comment]
...I Have problem with this new driver; the system freeze on startup

2011/6/9 andrea pini glaupin@tin.it:

**Comment by adlan** [comment]
sorry been quite busy for the last few days,

@jackblow, try loading the kext manually using kextutil (`sudo kextutil -v 4 BCM5722D.kext`) and paste here the log message after loading BCM5722D.kext (both kextutil and in /var/log/kernel.log, take the line starting with BCM5722D)

**Comment by jackblow** [comment]
Hi,

Ok now BCM5722D is perfectly working. I copied it in Sistema/ libreria
/ Extension, Than I started Kext Utility.app and now all ok.

thank you very very much

2011/6/10 adlan
reply@reply.github.com:
